### ISSUE TITLE
Native transport linkage issues

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#456]
### Expected Behavior

Running Elide's server intrinsic on macOS and Linux should produce performance (roughly) matching Elide's benchmarks.

### Actual Behaviour

Before launch, crashes were surfacing related to native transport and crypto linkage, so a fallback mechanism was added for NIO. As a result, NIO is selected in many cases, which degrades performance significantly.

### Stacktrace

N/A (Regression)

### Steps To Reproduce

1. Download Elide on macOS or Linux
2. Benchmark the JS server intrinsic script (`tools/scripts/server.js`)
3. Notice ~100ms of latency that should not be there

### Environment Information

- Operating System: N/A
- Architecture: N/A

### Runtime

Native

### Version

1.0.0-alpha7

**Comment by darvld** [comment]
@sgammon can we confirm if this is still happening after #475?

**Comment by sgammon** [comment]
@darvld i'll rebuild and check, yeah
