### ISSUE TITLE
Question: C++ interop

### ISSUE THREAD

**Issue by makslevental** [elide-dev/elide#689]
### Issue description

Sorry if this random and unwanted but I noticed you have [llvm.C++Interop](https://github.com/elide-dev/elide/blob/8716fd3c5c71f0d28d14581e47a6ec5b6a0a8423/packages/graalvm-py/src/main/kotlin/elide/runtime/plugins/python/Python.kt#L51) turned on in a couple of places - are there examples of C++ interop somewhere in-tree?

**Comment by darvld** [comment]
Hello, could you elaborate on what you are looking for regarding C++ interop? We are currently working on a native API that allows using Elide to dispatch calls from native applications, if that's the intent behind your question.

If you are referring to C++ interop from guest code being evaluated by Elide (e.g. a Python script using a C++ library), there are currently no samples or documentation about it, but we would be happy to hear about your use cases.

**Comment by makslevental** [comment]
I was interested in arbitrary C++ interop between whatever and however. I have since done the deep dive on graal and have figured out how to do it (with just graal). Thanks.

**Comment by sgammon** [comment]
@makslevental Sorry about the delay, GitHub notifications are legendarily bad. Yes, I think plain GraalVM would be better at this. If you haven't seen some of the [C interface stuff for GVM][1] (it's buried), that could help too. Feel free to file here or contact us on Discord and we'd be happy to help even if it's not related to Elide directly.

We are shipping a native interop layer soon (specifically, with WorkerD, which is in C++) so we have a lot of lessons which may or may not help.

[1]: https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.tutorial/src/com/oracle/svm/tutorial/CInterfaceTutorial.java

**Comment by makslevental** [comment]
> If you haven't seen some of the [C interface stuff for GVM](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.tutorial/src/com/oracle/svm/tutorial/CInterfaceTutorial.java) (it's buried)

Yes I've seen it and cribbed to implement https://github.com/makslevental/graalvm_cpp_interop

The principle takeaway (after the deep-dive and some follow-up discussions with graal people) is there's a hard limit on how much bitcode graal can parse because of the 32b limit on largest array size (the C++ interop lazily parses bitcode). This is unworkable for me because I want to bind a very large code base (all of LLVM in fact).

> We are shipping a native interop layer soon (specifically, with WorkerD, which is in C++) so we have a lot of lessons which may or may not help.

Not sure what "WorkerD" is but my next attempt (no clue when - day job) will involve just binding/using libclang itself.
