### ISSUE TITLE
Node: `assert` fails to raise assertion errors

### ISSUE THREAD

**Issue by darvld** [elide-dev/elide#949]
On `main`, when using the built-in `assert` module in a guest context, it should raise an assertion error:
```javascript
const assert = require("assert");

assert.equal(1, 0, "should fail") // throws AssertionError
```

However an obscure error is thrown instead, seemingly due to an issue with instantiating the assertion error itself:
```
org.graalvm.polyglot.PolyglotException: TypeError: s is not a constructor
        at <js>.m(assert.cjs:1)
```

> Note: The code for the `assert` module is minified during the build, so this stacktrace is not particularily helpful, maybe we should use non-minified code for debug builds and binaries to ease debugging.

After some more research, it seems the error will only be triggered if the "message" argument is passed, otherwise the function works as expected.

**Comment by sgammon** [comment]
Good catch

**Comment by darvld** [comment]
Failed to reproduce on latest commit, will reopen if spotted again. I'm not sure what may have caused it but so far it seems to have been a false positive.
